TRUNCATE staff RESTART IDENTITY CASCADE;

INSERT INTO "staff" ("name_en", "name_np", "role_en", "role_np", "department", "qualification", "display_order", "is_active") VALUES
('Puspa Raj Ojha', 'पुष्प राज ओझा', 'PRINCIPAL', 'प्रधानाध्यापक', 'administration', 'B.A', 1, true),
('Radhika Ojha', 'राधिका ओझा', 'Teacher (PG)', 'शिक्षिका (पी.जी)', 'teaching', 'I.Com', 2, true),
('Tulasi Bist', 'तुलसी विष्ट', 'Teacher (NURSERY)', 'शिक्षिका (नर्सरी)', 'teaching', 'I.Ed', 3, true),
('Kanchan B.C', 'कञ्चन बि.सी', 'Teacher (NURSERY)', 'शिक्षिका (नर्सरी)', 'teaching', NULL, 4, true),
('Sapura Shahi', 'सपुरा शाही', 'Teacher (LKG A)', 'शिक्षिका (एल.के.जी ए)', 'teaching', 'I.Ed', 5, true),
('Repti Rana', 'रेप्ती राणा', 'Teacher (LKG B)', 'शिक्षिका (एल.के.जी बी)', 'teaching', 'I.Ed', 6, true),
('Sher Bahadur B.K', 'शेर बहादुर बि.क', 'Teacher (UKG A)', 'शिक्षक (यु.के.जी ए)', 'teaching', 'I.Com', 7, true),
('Anjeela Tamang', 'अन्जीला तामाङ', 'Teacher (UKG B)', 'शिक्षिका (यु.के.जी बी)', 'teaching', 'I.Com', 8, true),
('Shushila Dhami', 'शुशिला धामी', 'Teacher (Class 1 A)', 'शिक्षिका (कक्षा १ ए)', 'teaching', 'B.Com', 9, true),
('Sohana Tamang', 'सोहना तामाङ', 'Teacher (Class 1 B)', 'शिक्षिका (कक्षा १ बी)', 'teaching', 'I.Ed', 10, true),
('Pratima Shreshtha', 'प्रतिमा श्रेष्ठ', 'Teacher (Class 2 A)', 'शिक्षिका (कक्षा २ ए)', 'teaching', 'I.Com', 11, true),
('Raj Kumar Rana', 'राज कुमार राणा', 'Teacher (Class 2 B)', 'शिक्षक (कक्षा २ बी)', 'teaching', 'LA', 12, true),
('Kopila Amgai', 'कोपिला अमगाई', 'Teacher (Class 3 A)', 'शिक्षिका (कक्षा ३ ए)', 'teaching', 'B.Ed', 13, true),
('Manisha Nepali', 'मनिषा नेपाली', 'Teacher (Class 3 B)', 'शिक्षिका (कक्षा ३ बी)', 'teaching', 'B.Ed', 14, true),
('Goma Joshi', 'गोमा जोशी', 'Teacher (Class 4 A)', 'शिक्षिका (कक्षा ४ ए)', 'teaching', 'B.Com', 15, true),
('Hansh Ram Rana', 'हंश राम राणा', 'Teacher (Class 4 B)', 'शिक्षक (कक्षा ४ बी)', 'teaching', 'B.Ed', 16, true),
('Bikram Karki', 'विक्रम कार्की', 'Teacher (Class 6)', 'शिक्षक (कक्षा ६)', 'teaching', 'B.Com', 17, true),
('Bal Bahadur B.K', 'बल बहादुर बि.क', 'Teacher (Class 7)', 'शिक्षक (कक्षा ७)', 'teaching', 'B.Ed', 18, true),
('Kanhaiya Rana', 'कन्हैया राणा', 'Teacher (Class 8)', 'शिक्षक (कक्षा ८)', 'teaching', 'I.Sce', 19, true),
('Durga Khadayat', 'दुर्गा खडायत', 'Office Assistant', 'कार्यालय सहायक', 'administration', '8 pass', 20, true),
('Tulasi Bayadi', 'तुलसी बयडी', 'Office Assistant', 'कार्यालय सहायक', 'administration', '8 pass', 21, true),
('Gayatri Joshi', 'गायत्री जोशी', 'ACCOUNTANT', 'लेखापाल', 'administration', 'B.Com', 22, true),
('Chetan Ojha', 'चेतन ओझा', 'COMPUTER OPERATOR', 'कम्प्युटर सञ्चालक', 'administration', 'SEE', 23, true),
('Dev lal Ojha', 'देव लाल ओझा', 'SMC Member', 'व्यवस्थापन समिति सदस्य', 'administration', NULL, 24, true),
('Ishwari Ojha', 'ईश्वरी ओझा', 'SMC Member', 'व्यवस्थापन समिति सदस्य', 'administration', NULL, 25, true),
('Bhagawati Joshi', 'भगवती जोशी', 'SMC Member', 'व्यवस्थापन समिति सदस्य', 'administration', NULL, 26, true),
('Harshit Ojha', 'हर्षित ओझा', 'SMC Member', 'व्यवस्थापन समिति सदस्य', 'administration', NULL, 27, true),
('Ganesh Joshi', 'गणेश जोशी', 'SMC Member', 'व्यवस्थापन समिति सदस्य', 'administration', NULL, 28, true),
('Madhabi Chaudhary', 'माधवी चौधरी', 'SMC Member', 'व्यवस्थापन समिति सदस्य', 'administration', NULL, 29, true),
('Surendra Singh Diyal', 'सुरेन्द्र सिंह दियाल', 'DRIVER', 'चालक', 'support', NULL, 30, true),
('Dev Bahadur Bist', 'देव बहादुर विष्ट', 'GUARD', 'पहरेदार', 'support', NULL, 31, true);
